M48
; DRILL file {KiCad (6.0.9-0)} date 2023 March 02, Thursday 18:42:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-02T18:42:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.9291Y-2.0866
X1.9291Y-4.4488
X4.8819Y-2.0866
X4.8819Y-4.4488
T0
M30
